import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  IconBell,
  IconBrandX,
  IconFeatherFilled,
  IconHome,
  IconMail,
  IconSearch,
} from "@tabler/icons-react";
import AuthGuard from "@/components/auth-guard";
import { CreatePostDialog } from "@/components/create-post-dialog";
import Navbar from "@/components/navbar";
import { SignInDrawerDialog } from "@/components/sign-in-drawer-dialog";
import { Button } from "@/components/ui/button";
import { UserDropdown } from "@/components/user-dropdown";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
      >
        <div className="flex justify-center max-w-7xl mx-auto">
          <header className="hidden sm:flex flex-col justify-between w-20 xl:w-2xs h-screen sticky top-0 px-2 py-4">
            <div className="flex flex-col gap-4 items-center xl:items-start">
              <div className="p-3 hover:bg-gray-100 rounded-full cursor-pointer w-min transition">
                <IconBrandX className="size-7" />
              </div>

              <AuthGuard>
                <Navbar />

                <CreatePostDialog
                  trigger={
                    <Button
                      size="lg"
                      className="w-min xl:w-[90%] rounded-full p-4 h-fit"
                    >
                      <span className="hidden xl:block font-bold text-lg">
                        Post
                      </span>
                      <IconFeatherFilled className="size-7 xl:hidden" />
                    </Button>
                  }
                />
              </AuthGuard>
            </div>

            <UserDropdown />
          </header>
          {children}
          <aside className="hidden lg:block w-87.5 ml-8 py-2 h-screen sticky top-0">
            <div className="sticky top-0 bg-white z-10 pb-2 pt-1">
              <div className="relative group">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none group-focus-within:text-blue-500">
                  <IconSearch className="size-5" />
                </div>
                <input
                  type="text"
                  placeholder="Search"
                  className="w-full bg-gray-100 text-white rounded-full py-3 pl-10 pr-4 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-black border border-transparent focus:border-blue-500 transition"
                />
              </div>
            </div>

            <div className="bg-gray-100 rounded-2xl mt-4 border border-gray-100">
              <h3 className="font-bold text-xl p-4 pb-0">Who to follow</h3>

              <div className="p-4 hover:bg-white/5 cursor-pointer transition flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-white"></div>
                <div className="flex-1 overflow-hidden">
                  <p className="font-bold truncate">Google</p>
                  <p className="text-sm truncate">@Google</p>
                </div>
                <button className="bg-white text-black font-bold px-4 py-1.5 rounded-full text-sm hover:bg-gray-200">
                  Follow
                </button>
              </div>
              <div className="p-4 hover:bg-white/5 cursor-pointer transition flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-green-500"></div>
                <div className="flex-1 overflow-hidden">
                  <p className="font-bold truncate">NVIDIA</p>
                  <p className="text-sm truncate">@nvidia</p>
                </div>
                <button className="bg-white text-black font-bold px-4 py-1.5 rounded-full text-sm hover:bg-gray-200">
                  Follow
                </button>
              </div>
            </div>
          </aside>
        </div>
        <AuthGuard
          fallback={
            <div className="fixed bottom-0 w-full bg-blue-500 text-white z-30">
              <div className="max-w-7xl mx-auto flex flex-col items-start justify-between gap-3 sm:flex-row sm:items-center p-4">
                <div>
                  <p className="text-xl sm:text-2xl font-semibold">
                    Don't miss what's happening
                  </p>
                  <p className="text-sm sm:text-base text-white/90">
                    People on X are the first to know.
                  </p>
                </div>

                <SignInDrawerDialog
                  trigger={
                    <Button className="rounded-full font-bold bg-white text-black hover:bg-gray-100">
                      Log in
                    </Button>
                  }
                />
              </div>
            </div>
          }
        >
          <div className="sm:hidden sticky bottom-0 w-full bg-white/85 backdrop-blur-md border-t border-gray-100 flex justify-around p-3 z-50">
            <a href="#" className="p-2">
              <IconHome className="size-6" />
            </a>
            <a href="#" className="p-2">
              <IconSearch className="size-6" />
            </a>
            <a href="#" className="p-2">
              <IconBell className="size-6" />
            </a>
            <a href="#" className="p-2">
              <IconMail className="size-6" />
            </a>
          </div>

          <CreatePostDialog
            trigger={
              <Button
                size="icon-lg"
                className="sm:hidden fixed bottom-20 right-4 rounded-full text-white z-50 p-3 size-fit"
              >
                <IconFeatherFilled className="size-6" />
              </Button>
            }
          />
        </AuthGuard>
      </body>
    </html>
  );
}
