/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile/$username/index'
import { Route as ApiElectricUsersRouteImport } from './routes/api/electric/users'
import { Route as ApiElectricRepostsRouteImport } from './routes/api/electric/reposts'
import { Route as ApiElectricPostsRouteImport } from './routes/api/electric/posts'
import { Route as ApiElectricNotificationsRouteImport } from './routes/api/electric/notifications'
import { Route as ApiElectricLikesRouteImport } from './routes/api/electric/likes'
import { Route as ApiElectricFollowsRouteImport } from './routes/api/electric/follows'
import { Route as ApiElectricFeedItemsRouteImport } from './routes/api/electric/feed-items'
import { Route as ApiElectricBookmarksRouteImport } from './routes/api/electric/bookmarks'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProfileUsernamePostPostIdRouteImport } from './routes/profile/$username/post/$postId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/profile/$username/',
  path: '/profile/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricUsersRoute = ApiElectricUsersRouteImport.update({
  id: '/api/electric/users',
  path: '/api/electric/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricRepostsRoute = ApiElectricRepostsRouteImport.update({
  id: '/api/electric/reposts',
  path: '/api/electric/reposts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricPostsRoute = ApiElectricPostsRouteImport.update({
  id: '/api/electric/posts',
  path: '/api/electric/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricNotificationsRoute =
  ApiElectricNotificationsRouteImport.update({
    id: '/api/electric/notifications',
    path: '/api/electric/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiElectricLikesRoute = ApiElectricLikesRouteImport.update({
  id: '/api/electric/likes',
  path: '/api/electric/likes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricFollowsRoute = ApiElectricFollowsRouteImport.update({
  id: '/api/electric/follows',
  path: '/api/electric/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricFeedItemsRoute = ApiElectricFeedItemsRouteImport.update({
  id: '/api/electric/feed-items',
  path: '/api/electric/feed-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricBookmarksRoute = ApiElectricBookmarksRouteImport.update({
  id: '/api/electric/bookmarks',
  path: '/api/electric/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernamePostPostIdRoute =
  ProfileUsernamePostPostIdRouteImport.update({
    id: '/profile/$username/post/$postId',
    path: '/profile/$username/post/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/electric/bookmarks': typeof ApiElectricBookmarksRoute
  '/api/electric/feed-items': typeof ApiElectricFeedItemsRoute
  '/api/electric/follows': typeof ApiElectricFollowsRoute
  '/api/electric/likes': typeof ApiElectricLikesRoute
  '/api/electric/notifications': typeof ApiElectricNotificationsRoute
  '/api/electric/posts': typeof ApiElectricPostsRoute
  '/api/electric/reposts': typeof ApiElectricRepostsRoute
  '/api/electric/users': typeof ApiElectricUsersRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/profile/$username/post/$postId': typeof ProfileUsernamePostPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/electric/bookmarks': typeof ApiElectricBookmarksRoute
  '/api/electric/feed-items': typeof ApiElectricFeedItemsRoute
  '/api/electric/follows': typeof ApiElectricFollowsRoute
  '/api/electric/likes': typeof ApiElectricLikesRoute
  '/api/electric/notifications': typeof ApiElectricNotificationsRoute
  '/api/electric/posts': typeof ApiElectricPostsRoute
  '/api/electric/reposts': typeof ApiElectricRepostsRoute
  '/api/electric/users': typeof ApiElectricUsersRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/profile/$username/post/$postId': typeof ProfileUsernamePostPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/electric/bookmarks': typeof ApiElectricBookmarksRoute
  '/api/electric/feed-items': typeof ApiElectricFeedItemsRoute
  '/api/electric/follows': typeof ApiElectricFollowsRoute
  '/api/electric/likes': typeof ApiElectricLikesRoute
  '/api/electric/notifications': typeof ApiElectricNotificationsRoute
  '/api/electric/posts': typeof ApiElectricPostsRoute
  '/api/electric/reposts': typeof ApiElectricRepostsRoute
  '/api/electric/users': typeof ApiElectricUsersRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/profile/$username/post/$postId': typeof ProfileUsernamePostPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/notifications'
    | '/api/events'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/electric/bookmarks'
    | '/api/electric/feed-items'
    | '/api/electric/follows'
    | '/api/electric/likes'
    | '/api/electric/notifications'
    | '/api/electric/posts'
    | '/api/electric/reposts'
    | '/api/electric/users'
    | '/profile/$username/'
    | '/profile/$username/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/notifications'
    | '/api/events'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/electric/bookmarks'
    | '/api/electric/feed-items'
    | '/api/electric/follows'
    | '/api/electric/likes'
    | '/api/electric/notifications'
    | '/api/electric/posts'
    | '/api/electric/reposts'
    | '/api/electric/users'
    | '/profile/$username'
    | '/profile/$username/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/bookmarks'
    | '/_authenticated/notifications'
    | '/api/events'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/electric/bookmarks'
    | '/api/electric/feed-items'
    | '/api/electric/follows'
    | '/api/electric/likes'
    | '/api/electric/notifications'
    | '/api/electric/posts'
    | '/api/electric/reposts'
    | '/api/electric/users'
    | '/profile/$username/'
    | '/profile/$username/post/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiEventsRoute: typeof ApiEventsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiElectricBookmarksRoute: typeof ApiElectricBookmarksRoute
  ApiElectricFeedItemsRoute: typeof ApiElectricFeedItemsRoute
  ApiElectricFollowsRoute: typeof ApiElectricFollowsRoute
  ApiElectricLikesRoute: typeof ApiElectricLikesRoute
  ApiElectricNotificationsRoute: typeof ApiElectricNotificationsRoute
  ApiElectricPostsRoute: typeof ApiElectricPostsRoute
  ApiElectricRepostsRoute: typeof ApiElectricRepostsRoute
  ApiElectricUsersRoute: typeof ApiElectricUsersRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
  ProfileUsernamePostPostIdRoute: typeof ProfileUsernamePostPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/profile/$username'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/users': {
      id: '/api/electric/users'
      path: '/api/electric/users'
      fullPath: '/api/electric/users'
      preLoaderRoute: typeof ApiElectricUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/reposts': {
      id: '/api/electric/reposts'
      path: '/api/electric/reposts'
      fullPath: '/api/electric/reposts'
      preLoaderRoute: typeof ApiElectricRepostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/posts': {
      id: '/api/electric/posts'
      path: '/api/electric/posts'
      fullPath: '/api/electric/posts'
      preLoaderRoute: typeof ApiElectricPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/notifications': {
      id: '/api/electric/notifications'
      path: '/api/electric/notifications'
      fullPath: '/api/electric/notifications'
      preLoaderRoute: typeof ApiElectricNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/likes': {
      id: '/api/electric/likes'
      path: '/api/electric/likes'
      fullPath: '/api/electric/likes'
      preLoaderRoute: typeof ApiElectricLikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/follows': {
      id: '/api/electric/follows'
      path: '/api/electric/follows'
      fullPath: '/api/electric/follows'
      preLoaderRoute: typeof ApiElectricFollowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/feed-items': {
      id: '/api/electric/feed-items'
      path: '/api/electric/feed-items'
      fullPath: '/api/electric/feed-items'
      preLoaderRoute: typeof ApiElectricFeedItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/bookmarks': {
      id: '/api/electric/bookmarks'
      path: '/api/electric/bookmarks'
      fullPath: '/api/electric/bookmarks'
      preLoaderRoute: typeof ApiElectricBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/post/$postId': {
      id: '/profile/$username/post/$postId'
      path: '/profile/$username/post/$postId'
      fullPath: '/profile/$username/post/$postId'
      preLoaderRoute: typeof ProfileUsernamePostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiEventsRoute: ApiEventsRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiElectricBookmarksRoute: ApiElectricBookmarksRoute,
  ApiElectricFeedItemsRoute: ApiElectricFeedItemsRoute,
  ApiElectricFollowsRoute: ApiElectricFollowsRoute,
  ApiElectricLikesRoute: ApiElectricLikesRoute,
  ApiElectricNotificationsRoute: ApiElectricNotificationsRoute,
  ApiElectricPostsRoute: ApiElectricPostsRoute,
  ApiElectricRepostsRoute: ApiElectricRepostsRoute,
  ApiElectricUsersRoute: ApiElectricUsersRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
  ProfileUsernamePostPostIdRoute: ProfileUsernamePostPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
