/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiRepostsRouteImport } from './routes/api/reposts'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiLikesRouteImport } from './routes/api/likes'
import { Route as ApiFollowsRouteImport } from './routes/api/follows'
import { Route as ApiFeedItemsRouteImport } from './routes/api/feed-items'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiBookmarksRouteImport } from './routes/api/bookmarks'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile/$username/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProfileUsernamePostPostIdRouteImport } from './routes/profile/$username/post/$postId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepostsRoute = ApiRepostsRouteImport.update({
  id: '/api/reposts',
  path: '/api/reposts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLikesRoute = ApiLikesRouteImport.update({
  id: '/api/likes',
  path: '/api/likes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFollowsRoute = ApiFollowsRouteImport.update({
  id: '/api/follows',
  path: '/api/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedItemsRoute = ApiFeedItemsRouteImport.update({
  id: '/api/feed-items',
  path: '/api/feed-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksRoute = ApiBookmarksRouteImport.update({
  id: '/api/bookmarks',
  path: '/api/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/profile/$username/',
  path: '/profile/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernamePostPostIdRoute =
  ProfileUsernamePostPostIdRouteImport.update({
    id: '/profile/$username/post/$postId',
    path: '/profile/$username/post/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/api/bookmarks': typeof ApiBookmarksRoute
  '/api/events': typeof ApiEventsRoute
  '/api/feed-items': typeof ApiFeedItemsRoute
  '/api/follows': typeof ApiFollowsRoute
  '/api/likes': typeof ApiLikesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/reposts': typeof ApiRepostsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/users': typeof ApiUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/profile/$username/post/$postId': typeof ProfileUsernamePostPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/api/bookmarks': typeof ApiBookmarksRoute
  '/api/events': typeof ApiEventsRoute
  '/api/feed-items': typeof ApiFeedItemsRoute
  '/api/follows': typeof ApiFollowsRoute
  '/api/likes': typeof ApiLikesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/reposts': typeof ApiRepostsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/users': typeof ApiUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/profile/$username/post/$postId': typeof ProfileUsernamePostPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/api/bookmarks': typeof ApiBookmarksRoute
  '/api/events': typeof ApiEventsRoute
  '/api/feed-items': typeof ApiFeedItemsRoute
  '/api/follows': typeof ApiFollowsRoute
  '/api/likes': typeof ApiLikesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/reposts': typeof ApiRepostsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/users': typeof ApiUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/profile/$username/post/$postId': typeof ProfileUsernamePostPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/notifications'
    | '/api/bookmarks'
    | '/api/events'
    | '/api/feed-items'
    | '/api/follows'
    | '/api/likes'
    | '/api/notifications'
    | '/api/posts'
    | '/api/reposts'
    | '/api/upload'
    | '/api/users'
    | '/api/auth/$'
    | '/profile/$username/'
    | '/profile/$username/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/notifications'
    | '/api/bookmarks'
    | '/api/events'
    | '/api/feed-items'
    | '/api/follows'
    | '/api/likes'
    | '/api/notifications'
    | '/api/posts'
    | '/api/reposts'
    | '/api/upload'
    | '/api/users'
    | '/api/auth/$'
    | '/profile/$username'
    | '/profile/$username/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/bookmarks'
    | '/_authenticated/notifications'
    | '/api/bookmarks'
    | '/api/events'
    | '/api/feed-items'
    | '/api/follows'
    | '/api/likes'
    | '/api/notifications'
    | '/api/posts'
    | '/api/reposts'
    | '/api/upload'
    | '/api/users'
    | '/api/auth/$'
    | '/profile/$username/'
    | '/profile/$username/post/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiBookmarksRoute: typeof ApiBookmarksRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiFeedItemsRoute: typeof ApiFeedItemsRoute
  ApiFollowsRoute: typeof ApiFollowsRoute
  ApiLikesRoute: typeof ApiLikesRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiPostsRoute: typeof ApiPostsRoute
  ApiRepostsRoute: typeof ApiRepostsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
  ProfileUsernamePostPostIdRoute: typeof ProfileUsernamePostPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reposts': {
      id: '/api/reposts'
      path: '/api/reposts'
      fullPath: '/api/reposts'
      preLoaderRoute: typeof ApiRepostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/likes': {
      id: '/api/likes'
      path: '/api/likes'
      fullPath: '/api/likes'
      preLoaderRoute: typeof ApiLikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/follows': {
      id: '/api/follows'
      path: '/api/follows'
      fullPath: '/api/follows'
      preLoaderRoute: typeof ApiFollowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed-items': {
      id: '/api/feed-items'
      path: '/api/feed-items'
      fullPath: '/api/feed-items'
      preLoaderRoute: typeof ApiFeedItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks': {
      id: '/api/bookmarks'
      path: '/api/bookmarks'
      fullPath: '/api/bookmarks'
      preLoaderRoute: typeof ApiBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/profile/$username'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/post/$postId': {
      id: '/profile/$username/post/$postId'
      path: '/profile/$username/post/$postId'
      fullPath: '/profile/$username/post/$postId'
      preLoaderRoute: typeof ProfileUsernamePostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiBookmarksRoute: ApiBookmarksRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiFeedItemsRoute: ApiFeedItemsRoute,
  ApiFollowsRoute: ApiFollowsRoute,
  ApiLikesRoute: ApiLikesRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiPostsRoute: ApiPostsRoute,
  ApiRepostsRoute: ApiRepostsRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
  ProfileUsernamePostPostIdRoute: ProfileUsernamePostPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
